<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE canciones [
    <!ELEMENT canciones (songs)*>
    <!ELEMENT songs (titulo, compositores, productores, sello, artista, fecha)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT compositores (compositor)>
    <!ELEMENT compositor (nombre, apellidos)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT productores (productor)>
    <!ELEMENT productor (nombre, apellidos)>
    <!ELEMENT sello (#PCDATA)>
    <!ELEMENT artista (#PCDATA)>
    <!ELEMENT fecha EMPTY>
    <!ATTLIST fecha dia CDATA #REQUIRED>
    <!ATTLIST fecha mes CDATA #REQUIRED>
    <!ATTLIST fecha anio CDATA #REQUIRED>
    <!ATTLIST songs duracion CDATA #REQUIRED>
    <!ATTLIST songs anio CDATA #REQUIRED>
    <!ATTLIST canciones titulo CDATA #REQUIRED>
]>
<canciones titulo="Título genérico">
    <songs duracion="4:47" anio="2008">
        <titulo>Give it 2 me</titulo>
        <compositores>
            <compositor>
                <nombre>Pharrell</nombre>
                <apellidos>Williams</apellidos>
            </compositor>
        </compositores>
        <productores>
            <productor>
                <nombre>Pharrell</nombre>
                <apellidos>Williams</apellidos>
            </productor>
        </productores>
        <sello>Warner Bros. Record</sello>
        <artista>Madonna</artista>
        <fecha dia="17" mes="5" anio="2008" />
    </songs>
</canciones>