<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE canciones [
<!ELEMENT canciones (cancion)* >
<!ELEMENT cancion (titulo, compositores, productores, sello, artista) >
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT compositores (compositor)>
<!ELEMENT compositor (nombre, apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA) >
<!ELEMENT productores (productor)>
<!ELEMENT productor (nombre, apellidos)>
<!ELEMENT sello (#PCDATA) >
<!ELEMENT artista (#PCDATA) >
<!ATTLIST cancion duracion CDATA #REQUIRED> 
<!ATTLIST cancion anio CDATA #REQUIRED>
]>
<canciones>
    <cancion duracion="4:47" anio="2008">
        <titulo>Give it 2 me</titulo>
        <compositores>
            <compositor>
                <nombre>Pharrell</nombre>
                <apellidos>Williams</apellidos>
            </compositor>
        </compositores>
        <productores>
            <productor>
                <nombre>Pharrell</nombre>
                <apellidos>Williams</apellidos>
            </productor>
        </productores>
        <sello>Warner Bros. Record</sello>
        <artista>Madonna</artista>
    </cancion>
</canciones>